services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
     - OLLAMA_HOST=0.0.0.0:11434
    networks:
     - integration_network 
    volumes:
     - ollama-data:/root/.ollama
        
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: webui
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - integration_network  
    volumes:
      - ollama-webui-data:/app/backend/data
    depends_on:
      - ollama
volumes:
  ollama-data:
  ollama-webui-data:
networks:
  integration_network:
   external: true  
